### ISSUE TITLE
Bump required ruby version to 2.5

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/ruby-style#26]
Pin rubocop to 1.8.1

Layout/AlignHash has been renamed to Layout/HashAlignment
Metrics/LineLength has been moved to Layout/LineLength
Naming/UncommunicativeMethodParamName has been renamed to Naming/MethodParameterName

Added but not enabled cops (gives message saying to explicitly enable/disable):
- Layout/SpaceBeforeBrackets: # (new in 1.7)
- Lint/AmbiguousAssignment: # (new in 1.7)
- Lint/DeprecatedConstants: # (new in 1.8)
- Lint/DuplicateBranch: # (new in 1.3)
- Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
- Lint/EmptyBlock: # (new in 1.1)
- Lint/EmptyClass: # (new in 1.3)
- Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
- Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
- Lint/RedundantDirGlobSort: # (new in 1.8)
- Lint/ToEnumArguments: # (new in 1.1)
- Lint/UnexpectedBlockArity: # (new in 1.5)
- Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
- Style/ArgumentsForwarding: # (new in 1.1)
- Style/CollectionCompact: # (new in 1.2)
- Style/DocumentDynamicEvalDefinition: # (new in 1.1)
- Style/EndlessMethod: # (new in 1.8)
- Style/HashExcept: # (new in 1.7)
- Style/NegatedIfElseCondition: # (new in 1.2)
- Style/NilLambda: # (new in 1.3)
- Style/RedundantArgument: # (new in 1.4)
- Style/SwapValues: # (new in 1.1)

**Comment by TheRoyalTnetennba** [comment]
To get google-cloud-ruby to pass:
```yaml
Lint/DuplicateRequire:
  Enabled: false
Lint/RedundantSafeNavigation:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/BeginEndAlignment:
  Enabled: false
Style/Proc:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
```
